# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the csi2115-f21 branch
  push:
    branches: [ master, csi2115-f21 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Webhook Trigger
        uses: zzzze/webhook-trigger@v1.0.0
        env:
          SEBASTIAN_CREDENTIALS:  ${{ secrets.SEBASTIAN_CREDENTIALS }}
        with:
          # Data to be posted
          data: '{"event_type": "webhook"}'
          webhook_url: https://api.github.com/repos/sebastianrcnt/scripts/dispatches
          options: "-H 'Authorization: token $SEBASTIAN_CREDENTIALS'"
