# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the csi2115-f21 branch
  push:
    branches: [ master, csi2115-f21 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Webhook Trigger
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            --request POST \
            --data '{"event_type": "webhook"}' \
            https://api.github.com/repos/sebastianrcnt/scripts/dispatches
      - name: Repository Dispatch
        # You may pin to the exact commit or the version.
        # uses: peter-evans/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          # A repo scoped GitHub Personal Access Token
          token: ${{ secrets.SEBASTIAN_CREDENTIALS }}
          # The full name of the repository to send the dispatch.
          repository: sebastianrcnt/scripts
          # A custom webhook event name.
          event-type: webhook
